package Imacro;

//WebDriver java snippet for Selenium generated by iMacros Editor

import java.util.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.*;
import org.openqa.selenium.chrome.ChromeDriver;


public class FromiMacros {

public static void main(String[] args) {
//Please set the correct path to your Chromedriver.exe file 
System.setProperty("webdriver.chrome.driver", "\\Chromedriver.exe" );
WebDriver driver = new ChromeDriver();

try {
List<WebElement> frames;
Set<String> tabs;
WebElement element;
//VERSION BUILD=12.6.505.4525
tabs = driver.getWindowHandles();
driver.switchTo().window(tabs.toArray(new String[0])[0]);
//'SET !PLAYBACKDELAY 0.28
//ONSECURITYDIALOG BUTTON=YES CONTINUE=YES
driver.get("https://10.246.33.14/siebel/app/edealer/enu?SWECmd=Login&SWEPL=1&SRN=&SWETS=1655801975371");
element = driver.findElement(By.name("SWEUserName"));
element.clear();
element.sendKeys("DERBCASSER");
//SET !ENCRYPTION NO
element = driver.findElement(By.name("SWEPassword"));
element.clear();
element.sendKeys("DERBCASSER0202");
element = driver.findElement(By.partialLinkText("Login"));
element.click();
element = driver.findElement(By.partialLinkText("Invoices"));
element.click();
element = driver.findElement(By.name("s_1_1_3_0"));
element.click();
element = driver.findElement(By.id("1_s_1_l_Invoice_Date"));
element.click();
element = driver.findElement(By.name("Invoice_Date"));
element.clear();
element.sendKeys("=21/06/2022");
element = driver.findElement(By.id("1_s_1_l_IBM_Invoice_Type"));
element.click();
element = driver.findElement(By.name("IBM_Invoice_Type"));
element.clear();
element.sendKeys("=Consolidated Invoice");
element = driver.findElement(By.name("s_1_1_0_0"));
element.click();
//'TAG POS=4 TYPE=TABLE ATTR=CLASS:ui-pg-table
//'TAG POS=1 TYPE=SPAN ATTR=CLASS:"ui-icon ui-icon-seek-prev siebui-mouse-down"
element = driver.findElement(By.id("s_at_m_1"));
element.click();
//SET !TIMEOUT_PAGE 500
element = driver.findElement(By.id("s_at_m_1-menu"));
element.click();
//SET !TIMEOUT_PAGE 500
element = driver.findElement(By.partialLinkText("Export..."));
element.click();
//ONSCRIPTERROR CONTINUE=YES
//ONDOWNLOAD FOLDER=D://Renault1234231 FILE=Abc.pdf WAIT=YES
//WebDriver cannot find an element by text unless it is a link.
//TAG POS=2 TYPE=SPAN ATTR=TXT:Next
//'TAG POS=1 TYPE=BUTTON ATTR=NAME:s_3_1_78_0
//'TAG POS=1 TYPE=BUTTON ATTR=NAME:s_2_1_78_0_Ctrl
//'SET !TIMEOUT_PAGE 500
//'TAG POS=1 TYPE=SPAN ATTR=CLASS:"ui-icon ui-icon-seek-next"
//'TAG POS=4 TYPE=TABLE ATTR=CLASS:ui-pg-table
//'TAG POS=1 TYPE=DIV ATTR=NAME:_sweview
//'TAG POS=4 TYPE=TABLE ATTR=CLASS:ui-pg-table
//'TAG POS=1 TYPE=TD ATTR=ID:"next_pager_s_1_l"
//'TAG POS=R1 TYPE=SPAN ATTR=CLASS:"ui-icon ui-icon-seek-next"
//'TAG POS=R1 TYPE=SPAN ATTR=TITLE:"Next record set"
//'TAG POS=1 TYPE=UL ATTR=TXT:"HomeRepair OrdersInvoicesVehiclesLiteratureBulletin Module"
//'TAG POS=1 TYPE=SPAN ATTR=TITLE:"Next record set"
//'TAG POS=1 TYPE=TD ATTR=ID:"next_pager_s_1_l"
//'Next record set'

}
catch (Exception e) {
System.out.println(e);
}
finally {
driver.close();
driver.quit();
} } }